[package]
name = "imageproc-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
imageproc = { version = "0.23.0", features = ["display-window"] }
rusttype = "0.9.3"